[package]
workspace = ".."
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
warp = "*"                                                                               
motordriver = { path = "../motordriver" }
tokio = {version = "1", features = [ "full" ]}
rppal = "0.12"
