[package]
workspace = ".."
name = "motordriver"
version = "0.1.0"
edition = "2021"

[features]
default = []
hardware = ["rppal"]

[dependencies]
log = "0.4"
anyhow = "1"
thiserror = "1"
rppal = {version = "0.13", optional = true}

