[package]
workspace = ".."
name = "backend"
version = "0.1.0"
edition = "2021"

[features]
default = ["hardware"]
hardware = ["motordriver/hardware"]

[dependencies]
motordriver = {path = "../motordriver", default-features=false}
tokio = {version = "1", features = ["full"]}
warp = "0.3"
