[package]
workspace = ".."
name = "backend"
version = "0.1.0"
edition = "2021"

[features]
default = []
hardware = ["motordriver/hardware"]

[dependencies]
motordriver = {path = "../motordriver"}#, default-features=false}
dotenvy = "0.15"
log = "0.4"
anyhow = "1"
thiserror = "1"
rust-embed = "6"
tokio = {version = "1", features = ["full", "tracing"]}
poem = {version = "1", features = ["static-files", "anyhow", "embed"]}

